const gemstones = [
  {
    name: 'Ruby',
    color: 'Red',
    zodiacSigns: ['Cancer', 'Leo', 'Aries'],
    birthMonths: [7],
    purposes: ['love', 'career', 'protection'],
    description: 'The Ruby, known as the "King of Gemstones," is a vibrant red precious stone symbolizing passion, love, and vitality. It has been prized by royalty for centuries and is one of the most valuable colored gemstones.',
    benefits: ['Enhances passion and love', 'Boosts confidence and motivation', 'Protects against negative energy', 'Improves blood circulation', 'Strengthens the heart'],
    image: 'https://images.unsplash.com/photo-1551122089-4e3e72477432?w=500',
    priceRange: { min: 5000, max: 50000 },
    category: 'precious',
    rating: 4.9,
  },
  {
    name: 'Emerald',
    color: 'Green',
    zodiacSigns: ['Taurus', 'Gemini', 'Virgo'],
    birthMonths: [5],
    purposes: ['wealth', 'health', 'love'],
    description: 'The Emerald is a stunning green gemstone symbolizing rebirth, growth, and prosperity. Known as the "Stone of Successful Love," it opens and nurtures the heart chakra and promotes emotional healing.',
    benefits: ['Attracts wealth and abundance', 'Enhances memory and intellect', 'Promotes emotional healing', 'Strengthens relationships', 'Improves vision and vitality'],
    image: 'https://images.unsplash.com/photo-1583937443532-1a40c737fe01?w=500',
    priceRange: { min: 8000, max: 80000 },
    category: 'precious',
    rating: 4.8,
  },
  {
    name: 'Blue Sapphire',
    color: 'Blue',
    zodiacSigns: ['Virgo', 'Libra', 'Capricorn'],
    birthMonths: [9],
    purposes: ['career', 'wealth', 'spiritual'],
    description: 'Blue Sapphire, also known as Neelam, is one of the fastest-acting gemstones. It symbolizes wisdom, royalty, and divine favor. It can bring dramatic positive changes when suited to the wearer.',
    benefits: ['Accelerates career growth', 'Brings financial prosperity', 'Enhances mental clarity', 'Protects from evil eye', 'Strengthens discipline'],
    image: 'https://images.unsplash.com/photo-1599707367812-042e4c84e4aa?w=500',
    priceRange: { min: 10000, max: 100000 },
    category: 'precious',
    rating: 4.7,
  },
  {
    name: 'Diamond',
    color: 'White',
    zodiacSigns: ['Aries', 'Taurus', 'Libra'],
    birthMonths: [4],
    purposes: ['love', 'wealth', 'health'],
    description: 'Diamond is the hardest known natural substance and symbolizes eternal love, purity, and invincibility. It amplifies energy, brings clarity, and enhances the qualities of other stones worn with it.',
    benefits: ['Symbol of eternal love', 'Enhances creativity', 'Brings clarity of mind', 'Attracts abundance', 'Strengthens immunity'],
    image: 'https://images.unsplash.com/photo-1586882829491-b81178aa622e?w=500',
    priceRange: { min: 20000, max: 500000 },
    category: 'precious',
    rating: 5.0,
  },
  {
    name: 'Pearl',
    color: 'White',
    zodiacSigns: ['Cancer', 'Gemini', 'Pisces'],
    birthMonths: [6],
    purposes: ['health', 'love', 'spiritual'],
    description: 'Pearl is a unique organic gemstone formed within oysters. It symbolizes purity, wisdom, and calm. Moti is especially beneficial for emotional balance and is the gemstone of the Moon.',
    benefits: ['Calms the mind and emotions', 'Enhances beauty and charm', 'Improves sleep quality', 'Strengthens relationships', 'Balances hormones'],
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500',
    priceRange: { min: 2000, max: 30000 },
    category: 'organic',
    rating: 4.5,
  },
  {
    name: 'Yellow Sapphire',
    color: 'Yellow',
    zodiacSigns: ['Pisces', 'Sagittarius', 'Leo'],
    birthMonths: [11],
    purposes: ['education', 'wealth', 'career'],
    description: 'Yellow Sapphire, known as Pukhraj, is the gemstone of Jupiter. It brings wisdom, prosperity, and good fortune. It is highly recommended for those seeking academic success and spiritual growth.',
    benefits: ['Enhances knowledge and wisdom', 'Brings wealth and prosperity', 'Improves marital happiness', 'Boosts academic performance', 'Strengthens Jupiter influence'],
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=500',
    priceRange: { min: 5000, max: 60000 },
    category: 'precious',
    rating: 4.8,
  },
  {
    name: 'Amethyst',
    color: 'Purple',
    zodiacSigns: ['Aquarius', 'Pisces', 'Sagittarius'],
    birthMonths: [2],
    purposes: ['spiritual', 'health', 'protection'],
    description: 'Amethyst is a beautiful purple quartz known as the "Stone of Sobriety." It promotes calmness, clarity, and spiritual awareness. It has been treasured since ancient times for its stunning beauty and legendary powers.',
    benefits: ['Promotes calm and peace', 'Enhances intuition', 'Aids in meditation', 'Relieves stress and anxiety', 'Purifies negative energy'],
    image: 'https://images.unsplash.com/photo-1576081544622-cfb8dbb421e0?w=500',
    priceRange: { min: 1000, max: 15000 },
    category: 'semi-precious',
    rating: 4.6,
  },
  {
    name: 'Garnet',
    color: 'Red',
    zodiacSigns: ['Capricorn', 'Aquarius', 'Scorpio'],
    birthMonths: [1],
    purposes: ['career', 'love', 'health'],
    description: 'Garnet is a deep red gemstone that symbolizes passion, energy, and regeneration. Known as the "Stone of Commitment," it revitalizes feelings and inspires love and devotion.',
    benefits: ['Boosts energy and vitality', 'Enhances commitment', 'Improves blood circulation', 'Protects travelers', 'Inspires love and devotion'],
    image: 'https://images.unsplash.com/photo-1611955167811-4711904bb9f8?w=500',
    priceRange: { min: 1500, max: 20000 },
    category: 'semi-precious',
    rating: 4.4,
  },
  {
    name: 'Aquamarine',
    color: 'Blue',
    zodiacSigns: ['Aquarius', 'Pisces', 'Gemini'],
    birthMonths: [3],
    purposes: ['health', 'spiritual', 'love'],
    description: 'Aquamarine, the "Stone of the Sea," has a calming blue-green color reminiscent of ocean waters. It promotes courage, clarity, and peaceful communication.',
    benefits: ['Calms nerves and reduces stress', 'Enhances communication', 'Protects during travel', 'Promotes courage', 'Soothes sore throats'],
    image: 'https://images.unsplash.com/photo-1610729509778-e6a4e4a1bb21?w=500',
    priceRange: { min: 3000, max: 25000 },
    category: 'semi-precious',
    rating: 4.5,
  },
  {
    name: 'Topaz',
    color: 'Yellow',
    zodiacSigns: ['Scorpio', 'Sagittarius', 'Leo'],
    birthMonths: [11],
    purposes: ['career', 'wealth', 'love'],
    description: 'Topaz is a versatile gemstone associated with strength, intelligence, and courage. Its golden warmth brings joy and generosity, and it has been valued across many cultures as a stone of good fortune.',
    benefits: ['Boosts confidence', 'Attracts success', 'Enhances creativity', 'Promotes joy and generosity', 'Strengthens digestion'],
    image: 'https://images.unsplash.com/photo-1583937443532-1a40c737fe01?w=500',
    priceRange: { min: 2000, max: 30000 },
    category: 'semi-precious',
    rating: 4.4,
  },
  {
    name: 'Opal',
    color: 'White',
    zodiacSigns: ['Libra', 'Scorpio', 'Cancer'],
    birthMonths: [10],
    purposes: ['love', 'spiritual', 'career'],
    description: 'Opal is a mesmerizing gemstone known for its play of colors. It symbolizes hope, creativity, and inspiration. Each opal is unique, displaying a kaleidoscope of colors that shift with the light.',
    benefits: ['Inspires creativity', 'Enhances imagination', 'Promotes emotional expression', 'Strengthens memory', 'Brings good fortune'],
    image: 'https://images.unsplash.com/photo-1551122089-4e3e72477432?w=500',
    priceRange: { min: 3000, max: 40000 },
    category: 'precious',
    rating: 4.6,
  },
  {
    name: 'Peridot',
    color: 'Green',
    zodiacSigns: ['Leo', 'Virgo', 'Gemini'],
    birthMonths: [8],
    purposes: ['health', 'wealth', 'protection'],
    description: 'Peridot is a vibrant olive-green gemstone known as the "Stone of Compassion." Born from volcanic fire, it carries the healing power of nature and promotes growth, renewal, and prosperity.',
    benefits: ['Promotes healing and renewal', 'Attracts prosperity', 'Reduces jealousy and resentment', 'Enhances confidence', 'Protects against negativity'],
    image: 'https://images.unsplash.com/photo-1599707367812-042e4c84e4aa?w=500',
    priceRange: { min: 2000, max: 18000 },
    category: 'semi-precious',
    rating: 4.3,
  },
  {
    name: 'Turquoise',
    color: 'Blue',
    zodiacSigns: ['Sagittarius', 'Scorpio', 'Aquarius'],
    birthMonths: [12],
    purposes: ['protection', 'health', 'spiritual'],
    description: 'Turquoise is one of the oldest known gemstones, revered by ancient civilizations. This sky-blue stone is a master healer that promotes wholeness, communication, and spiritual attunement.',
    benefits: ['Master healing stone', 'Protects from negative energy', 'Enhances communication', 'Promotes self-realization', 'Strengthens the immune system'],
    image: 'https://images.unsplash.com/photo-1610729509778-e6a4e4a1bb21?w=500',
    priceRange: { min: 1500, max: 15000 },
    category: 'semi-precious',
    rating: 4.5,
  },
  {
    name: 'Moonstone',
    color: 'White',
    zodiacSigns: ['Cancer', 'Libra', 'Pisces'],
    birthMonths: [6],
    purposes: ['love', 'health', 'spiritual'],
    description: 'Moonstone is a mystical gemstone that captures the magic of the moon. It promotes intuition, emotional balance, and new beginnings. Its ethereal glow (adularescence) makes it truly enchanting.',
    benefits: ['Enhances intuition', 'Promotes new beginnings', 'Balances emotions', 'Improves fertility', 'Calms emotional instability'],
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=500',
    priceRange: { min: 1000, max: 12000 },
    category: 'semi-precious',
    rating: 4.5,
  },
  {
    name: 'Rose Quartz',
    color: 'Pink',
    zodiacSigns: ['Taurus', 'Libra', 'Cancer'],
    birthMonths: [1, 10],
    purposes: ['love', 'health', 'spiritual'],
    description: 'Rose Quartz is the ultimate "Stone of Unconditional Love." Its gentle pink energy opens the heart chakra, promoting love, self-care, friendship, deep inner healing, and feelings of peace.',
    benefits: ['Attracts love and romance', 'Promotes self-love', 'Heals emotional wounds', 'Enhances compassion', 'Reduces stress and tension'],
    image: 'https://images.unsplash.com/photo-1576081544622-cfb8dbb421e0?w=500',
    priceRange: { min: 500, max: 8000 },
    category: 'semi-precious',
    rating: 4.7,
  },
  {
    name: 'Citrine',
    color: 'Yellow',
    zodiacSigns: ['Gemini', 'Scorpio', 'Leo'],
    birthMonths: [11],
    purposes: ['wealth', 'career', 'education'],
    description: 'Citrine is known as the "Merchant\'s Stone" for its ability to attract wealth and success. Its warm golden energy promotes optimism, motivation, and creative expression.',
    benefits: ['Attracts wealth and abundance', 'Boosts creativity', 'Enhances self-confidence', 'Promotes optimism', 'Aids in manifesting goals'],
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=500',
    priceRange: { min: 1000, max: 12000 },
    category: 'semi-precious',
    rating: 4.5,
  },
  {
    name: 'Lapis Lazuli',
    color: 'Blue',
    zodiacSigns: ['Taurus', 'Libra', 'Capricorn'],
    birthMonths: [9, 12],
    purposes: ['education', 'spiritual', 'career'],
    description: 'Lapis Lazuli is a deep blue stone with golden flecks, treasured since antiquity. Known as the "Stone of Wisdom," it stimulates intellectual ability, truth-seeking, and honest communication.',
    benefits: ['Enhances intellectual ability', 'Promotes truth and honesty', 'Stimulates wisdom', 'Boosts creativity', 'Enhances dream work'],
    image: 'https://images.unsplash.com/photo-1599707367812-042e4c84e4aa?w=500',
    priceRange: { min: 800, max: 10000 },
    category: 'semi-precious',
    rating: 4.4,
  },
  {
    name: 'Onyx',
    color: 'Black',
    zodiacSigns: ['Leo', 'Capricorn', 'Scorpio'],
    birthMonths: [7, 12],
    purposes: ['protection', 'career', 'health'],
    description: 'Black Onyx is a powerful protection stone that absorbs and transforms negative energy. It promotes strength of mind, self-confidence, and helps one to be at ease in their surroundings.',
    benefits: ['Powerful protection stone', 'Enhances self-control', 'Promotes vigor and stamina', 'Helps overcome fears', 'Grounds and stabilizes'],
    image: 'https://images.unsplash.com/photo-1611955167811-4711904bb9f8?w=500',
    priceRange: { min: 500, max: 6000 },
    category: 'semi-precious',
    rating: 4.3,
  },
  {
    name: 'Jade',
    color: 'Green',
    zodiacSigns: ['Pisces', 'Taurus', 'Libra'],
    birthMonths: [3, 8],
    purposes: ['wealth', 'health', 'love'],
    description: 'Jade is a sacred stone in many cultures, symbolizing serenity, purity, and wisdom. It attracts good luck and friendship, and promotes harmony and balance in all aspects of life.',
    benefits: ['Attracts good luck', 'Promotes harmony and balance', 'Supports physical healing', 'Encourages self-sufficiency', 'Brings serenity'],
    image: 'https://images.unsplash.com/photo-1583937443532-1a40c737fe01?w=500',
    priceRange: { min: 2000, max: 25000 },
    category: 'semi-precious',
    rating: 4.5,
  },
  {
    name: 'Tanzanite',
    color: 'Blue',
    zodiacSigns: ['Sagittarius', 'Gemini', 'Libra'],
    birthMonths: [12],
    purposes: ['spiritual', 'career', 'education'],
    description: 'Tanzanite is a rare and exotic gemstone found only in Tanzania. Its stunning violet-blue color represents transformation and spiritual awakening. It is one of the most sought-after modern gemstones.',
    benefits: ['Promotes spiritual growth', 'Enhances psychic abilities', 'Aids in communication', 'Transforms negative energy', 'Boosts self-awareness'],
    image: 'https://images.unsplash.com/photo-1610729509778-e6a4e4a1bb21?w=500',
    priceRange: { min: 8000, max: 70000 },
    category: 'precious',
    rating: 4.7,
  },
  {
    name: 'Red Coral',
    color: 'Red',
    zodiacSigns: ['Aries', 'Cancer', 'Scorpio'],
    birthMonths: [10],
    purposes: ['health', 'career', 'protection'],
    description: 'Red Coral, or Moonga, is an organic gemstone associated with Mars. It gives courage, energy, and physical strength. It is especially beneficial for overcoming obstacles and achieving success.',
    benefits: ['Boosts courage and confidence', 'Improves physical strength', 'Overcomes obstacles', 'Enhances leadership', 'Protects from evil eye'],
    image: 'https://images.unsplash.com/photo-1551122089-4e3e72477432?w=500',
    priceRange: { min: 1500, max: 20000 },
    category: 'organic',
    rating: 4.4,
  },
  {
    name: 'Tourmaline',
    color: 'Green',
    zodiacSigns: ['Libra', 'Virgo', 'Scorpio'],
    birthMonths: [10],
    purposes: ['protection', 'health', 'love'],
    description: 'Tourmaline comes in a rainbow of colors and is one of the most versatile healing stones. It is a powerful mental healer that balances the right and left hemispheres of the brain.',
    benefits: ['Powerful protective shield', 'Balances energy', 'Promotes compassion', 'Relieves stress', 'Enhances inspiration'],
    image: 'https://images.unsplash.com/photo-1583937443532-1a40c737fe01?w=500',
    priceRange: { min: 3000, max: 35000 },
    category: 'semi-precious',
    rating: 4.5,
  },
];

const users = [
  {
    name: 'Admin User',
    email: 'admin@gemstone.com',
    password: 'admin123',
    role: 'admin',
  },
  {
    name: 'Demo User',
    email: 'user@gemstone.com',
    password: 'user123',
    role: 'user',
    zodiacSign: 'Leo',
    birthMonth: 8,
    favoriteColor: 'Blue',
  },
];

export { gemstones, users };
